---
title: "Austin's Clustering"
author: "L. Austin Hadamuscin"
date: "4/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages
```{r}
library(sampling)
library(tidyverse)
library(rworldmap)
library(mclust)
```

## Data
```{r}
dat <- read.csv("C:/Users/hadamul/OneDrive/Graduate school/Semester 4/Data Mining/Data-Mining-Final-Project/life14.csv")
load("C:/Users/hadamul/OneDrive/Graduate school/Semester 4/Data Mining/Data-Mining-Final-Project/initKnnImp.RData")
```

## Data Scaling
```{r}
 dat_scaled <- scale(knnOutput)
```

# k-means

```{r warning=FALSE}
RNGkind (sample.kind = "Rounding")
set.seed(0)

nseeds <- 1000
nk <- 20
 
seeds <- ceiling(runif(nseeds,0,900000))
# 
# kmean_matrix  <- matrix(NA, nrow = nseeds, ncol = nk)
# 
# for (k in 1:nk) {
#   seed_iter = 0
#   for (s in seeds) {
# 
#     set.seed(s)
#     seed_iter <- seed_iter + 1
# 
#     kmean_matrix[seed_iter,k] <- kmeans(dat_scaled, centers = k)$tot.withinss
#   }
# }
# save(kmean_matrix, file = "kmean_matrix.RData")

load("kmean_matrix.RData")
```

```{r echo=FALSE}
plot(1:nk,apply(kmean_matrix, 2, min), 
     type = "b",
     ylab = "wss",
     xlab = "k")
```
- 4 or 5, we will see


## Finding the seed for the 4/5-means
```{r}
kmean_seed3 <- seeds[which(kmean_matrix[,3]==min(kmean_matrix[,3]))[1]]
kmean_seed4 <- seeds[which(kmean_matrix[,4]==min(kmean_matrix[,4]))[1]]
kmean_seed5 <- seeds[which(kmean_matrix[,5]==min(kmean_matrix[,5]))[1]]
kmean_seed6 <- seeds[which(kmean_matrix[,6]==min(kmean_matrix[,6]))[1]]
kmean_seed7 <- seeds[which(kmean_matrix[,7]==min(kmean_matrix[,7]))[1]]
```

## Doing the 4/5-means
```{r}
set.seed(kmean_seed3)
means3 <- kmeans(dat_scaled, centers = 3)
set.seed(kmean_seed4)
means4 <- kmeans(dat_scaled, centers = 4)
set.seed(kmean_seed5)
means5 <- kmeans(dat_scaled, centers = 5)
set.seed(kmean_seed6)
means6 <- kmeans(dat_scaled, centers = 6)
set.seed(kmean_seed7)
means7 <- kmeans(dat_scaled, centers = 7)

means3$withinss
means4$withinss
means5$withinss
means6$withinss
means7$withinss
```

## Grouping data into clusters
```{r}
clust3 <- cbind(dat[,1:3],cluster = means3$cluster,knnOutput)
clust4 <- cbind(dat[,1:3],cluster = means4$cluster,knnOutput)
clust5 <- cbind(dat[,1:3],cluster = means5$cluster,knnOutput)
clust6 <- cbind(dat[,1:3],cluster = means6$cluster,knnOutput)
clust7 <- cbind(dat[,1:3],cluster = means7$cluster,knnOutput)
```

## Clust 3 Graph
```{r message=FALSE}
clust3_map <- joinCountryData2Map(clust3, joinCode = "NAME", nameJoinColumn = "Country", )

par(mar=c(0,0,1,0))
mapCountryData(mapToPlot = clust3_map,
               nameColumnToPlot="cluster",
               catMethod="categorical",
               colourPalette = "rainbow")
```



## Clust 4 Graph
```{r}
clust4_map <- joinCountryData2Map(clust4, joinCode = "NAME", nameJoinColumn = "Country", verbose = T)

par(mar=c(0,0,1,0))
mapCountryData(mapToPlot = clust4_map,
               nameColumnToPlot="cluster",
               catMethod="categorical",
               colourPalette = "rainbow")
```



## Clust 5 Graph
```{r}
clust5_map <- joinCountryData2Map(clust5, joinCode = "NAME", nameJoinColumn = "Country", verbose = T)

par(mar=c(0,0,1,0))
mapCountryData(mapToPlot = clust5_map,
               nameColumnToPlot="cluster",
               catMethod="categorical",
               colourPalette = "rainbow")
```



# Model Based

```{r message=FALSE}
# mb_rep <- 20
# mb_matrix <- matrix(NA, 14, mb_rep)
# 
# for (k in 1:mb_rep) {
#   mb_matrix[,k] <- Mclust(knnOutput, k)$BIC
# }
# 
# save(mb_matrix,file = "mb_matrix.RData")


load("mb_matrix.RData")
```


```{r}
plot(x=1:20,
     y=apply(mb_matrix, 2, function(i) min(i,na.rm = T)),
     type = "b",
     xlab = "k",
     ylab = "BIC")
```
- Either 4 or 5 looks like the best k.

## Doing the model clustering with 4 and 5 clusters
```{r}
mb4 <- Mclust(knnOutput, 4, verbose = F)
mb5 <- Mclust(knnOutput, 5, verbose = F)
```

## Grouping data into clusters
```{r}
mbclust4 <- cbind(dat[,1:3],cluster = mb4$classification,knnOutput)
mbclust5 <- cbind(dat[,1:3],cluster = mb5$classification,knnOutput)
```

## Clust 4 Graph
```{r message=FALSE}
mbclust4_map <- joinCountryData2Map(mbclust4, joinCode = "NAME", nameJoinColumn = "Country", )

par(mar=c(0,0,1,0))
mapCountryData(mapToPlot = mbclust4_map,
               nameColumnToPlot="cluster",
               catMethod="categorical",
               colourPalette = "rainbow")
```

## Clust 5 Graph
```{r message=FALSE}
mbclust5_map <- joinCountryData2Map(mbclust5, joinCode = "NAME", nameJoinColumn = "Country", )

par(mar=c(0,0,1,0))
mapCountryData(mapToPlot = mbclust5_map,
               nameColumnToPlot="cluster",
               catMethod="categorical",
               colourPalette = "rainbow")
```