---
title: "Austin's Clustering"
author: "L. Austin Hadamuscin"
date: "4/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages
```{r}
library(sampling)
library(tidyverse)
library(rworldmap)
library(mclust)
```

## Data
```{r}
dat <- read.csv("C:/Users/drumm/OneDrive/Graduate school/Semester 4/Data Mining/Data-Mining-Final-Project/imputedData.csv")
```

## Data Scaling
```{r}
 dat_scaled <- scale(select(dat, -Country, -Measles, -HALE_Birth))
```

# k-means

```{r warning=FALSE}
RNGkind (sample.kind = "Rounding")
set.seed(0)

nseeds <- 1000
nk <- 20
 
seeds <- ceiling(runif(nseeds,0,900000))

# kmean_matrix  <- matrix(NA, nrow = nseeds, ncol = nk)
# 
# for (k in 1:nk) {
#   seed_iter = 0
#   for (s in seeds) {
# 
#     set.seed(s)
#     seed_iter <- seed_iter + 1
# 
#     kmean_matrix[seed_iter,k] <- kmeans(dat_scaled, centers = k)$tot.withinss
#   }
# }
# save(kmean_matrix, file = "kmean_matrix.RData")

load("kmean_matrix.RData")
```

```{r echo=FALSE}
plot(1:nk,apply(kmean_matrix, 2, min), 
     type = "l",
     ylab = "wss",
     xlab = "k")
```
- 4 or 5, we will see


## Finding the seed for the 2- & 6-means
```{r}
kmean_seed2 <- seeds[which(kmean_matrix[,2]==min(kmean_matrix[,2]))[1]]
kmean_seed4 <- seeds[which(kmean_matrix[,4]==min(kmean_matrix[,4]))[1]]
kmean_seed5 <- seeds[which(kmean_matrix[,5]==min(kmean_matrix[,5]))[1]]
kmean_seed6 <- seeds[which(kmean_matrix[,6]==min(kmean_matrix[,6]))[1]]
```

## Doing the 4/5-means
```{r}
set.seed(kmean_seed2)
means2 <- kmeans(dat_scaled, centers = 2)
set.seed(kmean_seed4)
means4 <- kmeans(dat_scaled, centers = 4)
set.seed(kmean_seed5)
means5 <- kmeans(dat_scaled, centers = 5)
set.seed(kmean_seed6)
means6 <- kmeans(dat_scaled, centers = 6)

means2$withinss
means6$withinss
```

## Grouping data into clusters
```{r}
clust2 <- cbind(select(dat, Country, HALE_Birth),cluster = means2$cluster,dat)
clust4 <- cbind(select(dat, Country, HALE_Birth),cluster = means4$cluster,dat)
clust5 <- cbind(select(dat, Country, HALE_Birth),cluster = means5$cluster,dat)
clust6 <- cbind(select(dat, Country, HALE_Birth),cluster = means6$cluster,dat)
```

## 5 Cluster Graph
```{r message=FALSE}
clust5_map <- joinCountryData2Map(clust5, joinCode = "NAME",
                                  nameJoinColumn = "Country")

par(mar=c(0,0,1,0))
mapCountryData(mapToPlot = clust5_map,
               nameColumnToPlot="cluster",
               catMethod="categorical",
               colourPalette = "rainbow",)
```

## 4 Cluster Graph
```{r message=FALSE}
clust4_map <- joinCountryData2Map(clust4, joinCode = "NAME",
                                  nameJoinColumn = "Country")

par(mar=c(0,0,1,0))
mapCountryData(mapToPlot = clust4_map,
               nameColumnToPlot="cluster",
               catMethod="categorical",
               colourPalette = "rainbow",)
```

## 2 Cluster Graph
```{r message=FALSE}
clust2_map <- joinCountryData2Map(clust2, joinCode = "NAME",
                                  nameJoinColumn = "Country")

par(mar=c(0,0,1,0))
mapCountryData(mapToPlot = clust2_map,
               nameColumnToPlot="cluster",
               catMethod="categorical",
               colourPalette = "rainbow",)
```


## 6 Cluster Graph
```{r message=FALSE}
clust6_map <- joinCountryData2Map(clust6, joinCode = "NAME", nameJoinColumn = "Country")

par(mar=c(0,0,1,0))
mapCountryData(mapToPlot = clust6_map,
               nameColumnToPlot="cluster",
               catMethod="categorical",
               colourPalette = "rainbow")
```



# Model Based

```{r message=FALSE}
mb_rep <- 20
mb_matrix <- matrix(NA, 14, mb_rep)

mb_dat <- select(dat, -Country,-Measles, -HALE_Birth)

# for (k in 1:mb_rep) {
#   mb_matrix[,k] <- Mclust(mb_dat, k)$BIC
# }
# 
# save(mb_matrix,file = "mb_matrix.RData")


load("mb_matrix.RData")
```


```{r}
plot(x=1:20,
     y=apply(mb_matrix, 2, function(i) min(i,na.rm = T)),
     type = "b",
     xlab = "k",
     ylab = "BIC")
```
- Either 4 or 5 looks like the best k.

## Doing the model clustering with 3 and 19 clusters
```{r}
# mb3 <- Mclust(mb_dat, 3, verbose = F)
# mb4 <- Mclust(mb_dat, 4, verbose = F)
# 
# save(mb3, file = "mb3.RData")
# save(mb4, file = "mb4.RData")

load("mb3.RData")
load("mb4.RData")

# round(mb3$parameters$mean)
```

## Grouping data into clusters
```{r}
mbclust3 <- cbind(select(dat, Country, HALE_Birth),cluster = mb3$classification,dat)
mbclust4 <- cbind(select(dat, Country, HALE_Birth),cluster = mb4$classification,dat)
```

## Clust 3 Graph
```{r message=FALSE}
mbclust3_map <- joinCountryData2Map(mbclust3, joinCode = "NAME", nameJoinColumn = "Country", )

par(mar=c(0,0,1,0))
mapCountryData(mapToPlot = mbclust3_map,
               nameColumnToPlot="cluster",
               catMethod="categorical",
               colourPalette = "rainbow")
```



## Clust 4 Graph
```{r message=FALSE}
mbclust4_map <- joinCountryData2Map(mbclust4, joinCode = "NAME", nameJoinColumn = "Country", )

par(mar=c(0,0,1,0))
mapCountryData(mapToPlot = mbclust4_map,
               nameColumnToPlot="cluster",
               catMethod="categorical",
               colourPalette = "rainbow")
```






```{r}
means2$centers
```

